server.port: 2077

spring:
  application:
    name: product-service

eureka:
 client:
   registerWithEureka: true
   fetch-registry: true
   serverUrl:
     defaultZone: http://${DISCOVERY_NAME:localhost}:${DISCOVERY_PORT:8761}/eureka
   instance:
     hostname: 172.18.93.174
     ip-address: 172.18.93.174
     prefer-ip-address: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

opentracing:
  jaeger:
    http-sender:
      url: http://${JAEGER_HTTP_SENDER_HOST:jaeger}:${JAEGER_HTTP_SENDER_PORT:14268}/api/traces
