server.port: 2077

spring:
  application:
    name: product-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces
