server.port: 2077

spring:
  application:
    name: product-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: {cipher}AQAVh/ISDhowPm9MnrS8Wm8QoRtXcNhBE44zMSUGGPHj7h7F3Gw5Br350XanOuo78XnXEDVNDGCa6nv8/ZFyaMW5E4Que2JaMdH2RNfmCuDNafySsUGXrNtZSWddKg+GJAWw3UmKiaXLc3J4Agbwh2mYE22sAlY9YiR7ICptqiDcE85BYM5LobO27wJMF0qUzzO5CG1Fe7DR0qL99kYDZRM5yAb300emuLWd7/wqnvdCM52WlSPNFUW+shfhQl+vFW8rSDSucML4i0QLth751vFV/++5yh9JqHo5roXQMHCRxrXg/Jqe41APVdmvn1dVOPFxIHnxFGYpEdhxU1+H4JmoKzWcCzAxPdFf12Iwaa3GwWsK6NX5nhamj0NWkNgTX4U=

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831
    log-spans: true